# $OpenBSD$

LIB=	LLVMHelloNew
NOPROFILE=

CPPFLAGS+=	-I${LLVM_SRCS}/include/llvm/Transforms
CPPFLAGS+=	-I${LLVM_SRCS}/include/llvm/Transforms/HelloNew

SRCS+=	HelloWorld.cpp

.PATH:	${.CURDIR}/../../../llvm/llvm/lib/Transforms/HelloNew
